language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-head
  - 2.2.3
os:
  - linux
branches:
  except:
    - gh-pages
install:
  - bundle install
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec middleman build
  - 'PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} bundle exec pronto run -f github_pr'
